// uni-app/src/pages/index/index.vue
<template>
  <view>
    <view class="uni-list">
      <view class="uni-list-cell" v-for="(value,key) in listData" :key="key">
        <view style="flex:1">
          <card :item="value"></card>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import card from "components/card";
import Api from "utils/api.js";

export default {
  data() {
    return {
      listData: []
    };
  },
  components: {
    card
  },
  onLoad() {
    setTimeout(() => {
      this.$mp.page.$perf && this.$mp.page.$perf.mark("setData");
      this.listData = Api.getNews();
    }, 1000);
  },
  onPullDownRefresh() {
    this.listData = Api.getNews();
    setTimeout(() => {
      uni.showToast({
        title:"刷新成功"
      })
      uni.stopPullDownRefresh();
    }, 1000);
  },
  onReachBottom() {
    this.$mp.page.$perf && this.$mp.page.$perf.mark("setData");
    this.listData.push(...Api.getNews());
  }
};
</script>

<style>
/* 列表 */
.uni-list {
  background-color: #eee;
  position: relative;
  width: 100%;
  display: flex;
  flex-direction: column;
}
</style>

// taro/src/pages/index/index.jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Card from '../../components/card/card'
import Api from '../../utils/api'

import './index.css'

export default class Index extends Component {
 
  constructor(props) {
    super(props)
    this.state = {
      listData: []
    }
  }
  componentWillMount() {
    if (process.env.TARO_ENV === 'weapp') {
      this.$scope && this.$scope.$perf && this.$scope.$perf.mark('setData')
    }

    this.setState({
      listData: Api.getNews()
    })
  }

  onPullDownRefresh() {
    this.setState({
      listData: Api.getNews()
    })
    setTimeout(() => {
      Taro.stopPullDownRefresh()
      Taro.showToast({
        title: '刷新成功',
        duration: 1000
      })
    }, 1000)
  }

  onReachBottom() {
    this.$scope && this.$scope.$perf && this.$scope.$perf.mark('setData')
    let listData = this.state.listData
    listData.push(...Api.getNews())
    this.setState({
      listData
    })
  }
  config = {
    navigationBarTitleText: '仿微博 - taro版',
    enablePullDownRefresh: true,
    backgroundTextStyle: 'dark'
  }


  render() {
    const list = this.state.listData.map((item) => {
      return (
        <View className='uni-list-cell' key={item.id}>
          <View className='uni-list-cell-warp'>
            <Card item={item} />
          </View>
        </View>
      )
    })

    return (
      <View className='index'>
        <View class='uni-list'>{list}</View>
      </View>
    )
  }
}
