// uni-app/src/pages/index/index.vue
<template>
    <view>
        <view class="uni-list">
            <view class="uni-list-cell" v-for="(value,key) in listData" :key="key">
                <view style="flex:1">
                    <card :item="value"></card>
                </view>
            </view>
        </view>
    </view>
</template>

<script>
    import card from 'components/card'
    import Api from 'utils/api.js'

    export default {
        data() {
            return {
                listData: []
            }
        },
        components: {
            card
        },
        onLoad() {
            this.$mp.page.$perf && this.$mp.page.$perf.mark('setData')
            this.listData = Api.getNews()
        },
        onPullDownRefresh() {
            this.listData = Api.getNews()
            setTimeout(() => {
                uni.stopPullDownRefresh()
            }, 1000)
        },
        onReachBottom() {
            this.$mp.page.$perf && this.$mp.page.$perf.mark('setData')
            this.listData.push(
                ...Api.getNews().sort(function() {
                    return 0.5 - Math.random()
                })
            )
        }
    }
</script>

<style>
    /* 列表 */
    .uni-list {
        background-color: #eee;
        position: relative;
        width: 100%;
        display: flex;
        flex-direction: column;
    }
</style>

// taro/src/pages/index/index.tsx
import Taro, { Component, Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Card from '../../components/card/card'
import Api from '../../utils/api'

import './index.scss'

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页',
    enablePullDownRefresh: true,
    backgroundTextStyle: 'dark'
  }

  constructor(props) {
    super(props)
    this.state = {}
  }
  componentDidMount() {
    this.$scope.$perf && this.$scope.$perf.mark('setData')
    this.setState({
      listData: Api.getNews()
    })
  }
  
  onPullDownRefresh() {
    this.setState({
      listData: Api.getNews()
    })
    setTimeout(() => {
      Taro.stopPullDownRefresh()
    }, 1000)
  }
  
  onReachBottom() {
    this.$scope.$perf && this.$scope.$perf.mark('setData')
    const listData = this.state.listData
    listData.push(...Api.getNews().sort(function() {
      return .5 - Math.random();
    }))
    this.setState({
      listData
    })
  }
 
  render() {
    const list = this.state.listData.map((item, index) => {
      return (
        <View className="uni-list-cell" key={index}>
          <View className="uni-list-cell-warp">
            <Card item={item} />
          </View>
        </View>
      )
    })

    return (
      <View className="index">
        <View class="uni-list">{list}</View>
      </View>
    )
  }
}
