// uni-app-v3/src/pages/index/index.vue
<template>
    <view>
        <view class="uni-list">
            <view class="uni-list-cell" v-for="(value,key) in listData" :key="key">
                <view style="flex:1">
                    <card :item="value"></card>
                </view>
            </view>
        </view>
    </view>
</template>

<script>

    import card from "components/card";
    import Api from "utils/api.js";

    export default {
        data() {
            return {
                listData: []
            };
        },
        components: {
            card
        },
        setup(props, ctx) {
            let listData = reactive([])
            const pages = getCurrentPages()
            const page = pages[pages.length-1]
            setTimeout(() => {
                page.$perf && page.$perf.mark("setData");
                listData.push(...Api.getNews());
            }, 1000);
            onPullDownRefresh(function() {
                listData.length=0;
                listData.push(...Api.getNews());
                setTimeout(() => {
                    uni.showToast({
                        title: "刷新成功"
                    })
                    uni.stopPullDownRefresh();
                }, 1000);
            })
            onReachBottom(function() {
                page.$perf && page.$perf.mark("setData");
                listData.push(...Api.getNews());
            })
            return {
                listData
            }
        }
    };
</script>

<style>
    /* 列表 */
    .uni-list {
        background-color: #eee;
        position: relative;
        width: 100%;
        display: flex;
        flex-direction: column;
    }
</style>

// taro-next/src/pages/index/index.jsx
import React, { Component } from 'react'
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'
import Card from '../../components/card/card'
import Api from '../../utils/api'

import './index.css'


export default class Index extends Component {
  constructor(props) {
    super(props)
    this.state = {
      listData: []
    }
  }
  componentWillMount= () => {
    let pages = getCurrentPages()
    pages = pages[pages.length -1]
    if (process.env.TARO_ENV === 'weapp') {
      pages.$perf && pages.$perf.mark('setData')
    }

    this.setState({
      listData: Api.getNews()
    })
  }

  onPullDownRefresh() {
    this.setState({
      listData: Api.getNews()
    })
    setTimeout(() => {
      Taro.stopPullDownRefresh()
      Taro.showToast({
        title: '刷新成功',
        duration: 1000
      })
    }, 1000)
  }

  onReachBottom() {
    let pages = getCurrentPages()
    pages = pages[pages.length -1]
    pages.$perf && pages.$perf.mark('setData')
    let listData = this.state.listData
    listData.push(...Api.getNews())
    this.setState({
      listData
    })
  }

  render() {
    const list = this.state.listData.map((item,index) => {
      return (
        <View className='uni-list-cell' key={index}>
          <View className='uni-list-cell-warp'>
            <Card item={item} />
          </View>
        </View>
      )
    })

    return (
      <View className='index'>
        <View class='uni-list'>{list}</View>
      </View>
    )
  }
}
